name = "ProjectEulerTasks"
uuid = "25ca1e5d-f751-4774-ae6d-7444e4b6cb99"
authors = ["ludwig-austermann <ludwig.austermann@outlook.com> and contributors"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
